apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - image: demoacrxl.azurecr.io/jenkins
          name: jenkins
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-reg
